### ISSUE TITLE
getAttribute always return null

### ISSUE THREAD

**Issue by dongleiw** [mdn/web-components-examples#33] opened 2021-02-06 03:14 UTC
What I do

// main.js
```

class Test extends HTMLElement{
    constructor(){
        super()
        let shadow = this.attachShadow({mode:'open'});

        let text = this.getAttribute('text')
        if(text==null || text=="")
            text = 'null'

        let e = document.createElement("h3")
        e.textContent = text
        shadow.appendChild(e);
    }
}

window.customElements.define('my-test', Test);

```

```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>React App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

    <script src="./main.js"></script>              # script line
    <my-test text="hello webcomponent"/>  # element line
  </body>
</html>

```

I tried ff85 and  chrom88, it always print 'null' on the page. 
I have read this issue https://github.com/mdn/web-components-examples/issues/22 , it worked, but I don't understand. 

* browser parse the script line, get element name and element definition
* browser parse the element line, get attribute. 
* find the element definition by `my-test`, create instance using the constructor. In the constructor, attribute should already exists. But it not.

Please tell my where i am wrong. Thank you.

**Comment by Leokuma** [comment] 2021-02-06 22:30
The `connectedCallback` is more appropriate to achieve what you want instead of the `constructor`.

This is from the [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance):

> The element's attributes and children must not be inspected, as in the non-upgrade case none will be present

If your custom element (JS) is defined before the custom element in the DOM, your element will be "non-upgraded" and its attributes will not be available in the constructor.

Another reason not to use the constructor is that if you create your element dynamically with `createElement` or with the class constructor itself, the constructor will run immediately, before the dev has any chance to add attributes.

**Comment by Rumyra** [comment] 2022-05-06 10:05
Duplicate of #34

**Closed by Rumyra** 2022-05-06 10:05 UTC
